// Additional question banks: three trades (plumbing, electrical, HVAC) plus
// topic expansions for alcohol, medical, and USA & Canada. Kept separate to
// keep trivia.js manageable. Duplicate questions are removed at runtime.
//
// CONVENTION: the correct option is listed FIRST (answer: 0). Option order is
// shuffled at game time (shuffleQuestion in trivia.js), so there's no player-
// facing position bias — but if you reorder options, keep the right one at
// index 0 (or update `answer`). validateBanks() in trivia.js flags mistakes.

export const plumbing = [
  { q: "What is the primary purpose of a P-trap under a sink?", options: ["To hold water that blocks sewer gases from entering the home", "To slow down the flow of water into the drain", "To filter debris before it reaches the main line", "To increase water pressure at the faucet"], answer: 0 },
  { q: "Which pipe material is a flexible plastic tubing often used for modern water supply lines?", options: ["PEX", "Cast iron", "Galvanized steel", "ABS"], answer: 0 },
  { q: "What does the abbreviation DWV stand for in plumbing?", options: ["Drain-waste-vent", "Direct water valve", "Drainage water volume", "Dual water vent"], answer: 0 },
  { q: "Why are horizontal drain lines installed with a downward slope?", options: ["So gravity carries waste and water toward the sewer", "To raise the water pressure in the line", "To prevent the pipes from freezing", "To reduce the amount of pipe material needed"], answer: 0 },
  { q: "What is the common joining method for copper pipe using heat and solder?", options: ["Sweating", "Crimping", "Gluing", "Threading"], answer: 0 },
  { q: "Which black plastic pipe is commonly used for drain and waste lines?", options: ["ABS", "PEX", "Copper", "CPVC"], answer: 0 },
  { q: "What safety device on a water heater opens if temperature or pressure gets too high?", options: ["Temperature and pressure relief valve", "Check valve", "Gate valve", "Ball valve"], answer: 0 },
  { q: "What hand tool is most associated with gripping and turning pipes?", options: ["Pipe wrench", "Claw hammer", "Tape measure", "Putty knife"], answer: 0 },
  { q: "What is the main advantage of a tankless water heater over a tank model?", options: ["It heats water on demand rather than storing it", "It never needs electricity or gas", "It works without any water supply", "It stores far more hot water"], answer: 0 },
  { q: "What thin white tape is wrapped on threaded pipe joints to help seal them?", options: ["Teflon tape", "Electrical tape", "Duct tape", "Masking tape"], answer: 0 },
  { q: "Which fitting is used to change the direction of a pipe run?", options: ["Elbow", "Coupling", "Union", "Nipple"], answer: 0 },
  { q: "Which fitting connects three pipes in a T shape?", options: ["Tee", "Elbow", "Cap", "Bushing"], answer: 0 },
  { q: "What is the simplest tool used to clear a clogged toilet or drain by suction?", options: ["Plunger", "Basin wrench", "Pipe cutter", "Hacksaw"], answer: 0 },
  { q: "What flexible tool is fed into a drain to break up or pull out clogs?", options: ["Drain auger or snake", "Torque wrench", "Caulk gun", "Stud finder"], answer: 0 },
  { q: "What specialized tool reaches up behind a sink to turn faucet mounting nuts?", options: ["Basin wrench", "Pipe wrench", "Channel-lock pliers", "Allen wrench"], answer: 0 },
  { q: "What is backflow in a plumbing system?", options: ["The unwanted reverse flow of water back into the supply", "The normal flow of water down a drain", "Water heating up too quickly", "Air trapped inside a pipe"], answer: 0 },
  { q: "Which older metal pipe is prone to internal rust and reduced flow over time?", options: ["Galvanized steel", "PEX", "Copper", "PVC"], answer: 0 },
  { q: "What is the purpose of a vent pipe in a drainage system?", options: ["To let air in so drains flow smoothly and traps are not siphoned", "To supply hot water to fixtures", "To increase water pressure", "To filter out sewer odors chemically"], answer: 0 },
  { q: "Which valve uses a rotating ball with a hole to start or stop flow with a quarter turn?", options: ["Ball valve", "Gate valve", "Globe valve", "Check valve"], answer: 0 },
  { q: "What does PVC stand for as a plumbing pipe material?", options: ["Polyvinyl chloride", "Pressed vinyl compound", "Plastic vacuum coil", "Polymer vent casing"], answer: 0 },
  { q: "What is a typical range for residential water pressure?", options: ["About 40 to 60 psi", "About 5 to 10 psi", "About 150 to 200 psi", "About 300 to 400 psi"], answer: 0 },
  { q: "Which white plastic pipe can handle hot water and is rated for supply lines?", options: ["CPVC", "ABS", "Standard PVC", "Cast iron"], answer: 0 },
  { q: "What is the function of a shut-off valve under a sink or toilet?", options: ["To stop water to that fixture for repairs", "To boost water temperature", "To vent sewer gas", "To measure water flow"], answer: 0 },
  { q: "What fitting joins two straight pipes of the same diameter end to end?", options: ["Coupling", "Elbow", "Tee", "Reducer"], answer: 0 },
  { q: "What fitting allows two pipes to be joined and later disconnected without cutting?", options: ["Union", "Coupling", "Elbow", "Cap"], answer: 0 },
  { q: "In a home with a septic system, where does household wastewater first go?", options: ["Into an on-site septic tank and drain field", "Into the municipal sewer main", "Into the storm drain", "Back into the freshwater supply"], answer: 0 },
  { q: "What is the main reason copper pipe is valued for water supply?", options: ["It is durable and resists corrosion", "It is the cheapest material available", "It can be installed without any fittings", "It never needs to be supported"], answer: 0 },
  { q: "What commonly causes a P-trap to lose its water seal?", options: ["Evaporation or siphoning of the trap water", "Too much water pressure in the supply", "Using hot water in the sink", "Closing the shut-off valve"], answer: 0 },
  { q: "Which valve is best for fully open or fully closed service but not throttling?", options: ["Gate valve", "Globe valve", "Needle valve", "Diaphragm valve"], answer: 0 },
  { q: "What heavy, durable pipe was widely used for drains in older homes?", options: ["Cast iron", "PEX", "CPVC", "Copper"], answer: 0 },
  { q: "What tool makes a clean, square cut on copper or plastic tubing?", options: ["Tube cutter", "Basin wrench", "Plunger", "Pipe reamer"], answer: 0 },
  { q: "Why should burrs be removed from the inside of a freshly cut pipe?", options: ["To prevent flow restriction and turbulence", "To make the pipe longer", "To add water pressure", "To help solder stick to the outside"], answer: 0 },
  { q: "What is the term for water that supplies fixtures under pressure?", options: ["Supply or potable water", "Waste water", "Vent air", "Gray water"], answer: 0 },
  { q: "What is applied to clean copper before soldering a joint?", options: ["Soldering flux", "Pipe dope for threads", "Silicone caulk", "Plumbers putty"], answer: 0 },
  { q: "Which material requires solvent cement rather than heat to join?", options: ["PVC", "Copper", "Galvanized steel", "Cast iron"], answer: 0 },
  { q: "What is a common symptom of a clogged or restricted vent?", options: ["Gurgling drains and slow drainage", "Higher water pressure at faucets", "Hotter water from the heater", "Constant running of the supply line"], answer: 0 },
  { q: "What is the purpose of a sacrificial anode rod in a tank water heater?", options: ["To corrode in place of the tank and reduce rust", "To heat the water faster", "To regulate water pressure", "To vent gas from the tank"], answer: 0 },
  { q: "What does a check valve do?", options: ["Allows water to flow in only one direction", "Mixes hot and cold water", "Measures water usage", "Slows the drain flow"], answer: 0 },
  { q: "What is plumbers putty typically used for?", options: ["Sealing around fixtures like sink drains and faucets", "Joining copper pipe", "Sealing threaded gas lines", "Insulating hot pipes"], answer: 0 },
  { q: "Which connection method for PEX uses a ring crimped around the fitting?", options: ["Crimp ring connection", "Solder joint", "Solvent weld", "Threaded joint"], answer: 0 },
  { q: "What distinguishes a sewer system from a septic system?", options: ["A sewer carries waste to a municipal treatment plant", "A sewer stores waste in a backyard tank", "A sewer supplies drinking water", "A sewer only handles rainwater"], answer: 0 },
  { q: "What fitting is used to cap or close the end of a pipe?", options: ["Cap", "Tee", "Union", "Elbow"], answer: 0 },
  { q: "Why is a water heater relief valve usually piped to discharge near the floor?", options: ["So released hot water or steam does not spray and injure someone", "To increase the tank capacity", "To raise the water temperature", "To improve water taste"], answer: 0 },
  { q: "What is water hammer in a plumbing system?", options: ["A banging noise from a sudden stop in water flow", "A tool for breaking concrete", "A type of pipe fitting", "A method of soldering"], answer: 0 },
  { q: "What does a typical residential toilet use to create flush and refill?", options: ["A tank, flapper, and fill valve", "A compressor and tank", "A circulating pump", "A pressure regulator only"], answer: 0 },
];

export const electrical = [
  { q: "What is the standard voltage for most general-purpose receptacle circuits in a US home?", options: ["120 volts", "240 volts", "12 volts", "480 volts"], answer: 0 },
  { q: "What is the typical voltage supplied to a US electric clothes dryer or range?", options: ["240 volts", "120 volts", "24 volts", "600 volts"], answer: 0 },
  { q: "What is the maximum breaker size normally used to protect 14 AWG copper wire?", options: ["15 amps", "20 amps", "30 amps", "40 amps"], answer: 0 },
  { q: "What size breaker is normally used with 12 AWG copper wire?", options: ["20 amps", "15 amps", "30 amps", "50 amps"], answer: 0 },
  { q: "What size breaker is normally used with 10 AWG copper wire?", options: ["30 amps", "15 amps", "20 amps", "60 amps"], answer: 0 },
  { q: "In US wiring, what color is the insulation on a standard hot conductor?", options: ["Black", "White", "Green", "Gray"], answer: 0 },
  { q: "In US wiring, what color identifies the neutral conductor?", options: ["White", "Black", "Red", "Green"], answer: 0 },
  { q: "In US wiring, what color is used for the equipment grounding conductor?", options: ["Green", "Black", "White", "Blue"], answer: 0 },
  { q: "A bare copper wire in a US cable normally serves as which conductor?", options: ["Ground", "Hot", "Neutral", "Switched hot"], answer: 0 },
  { q: "What does Ohm's law state?", options: ["Voltage equals current times resistance", "Voltage equals current divided by resistance", "Current equals voltage times resistance", "Power equals voltage times resistance"], answer: 0 },
  { q: "How is electrical power in watts calculated in a basic DC circuit?", options: ["Volts times amps", "Volts divided by amps", "Amps divided by volts", "Volts plus amps"], answer: 0 },
  { q: "What is the unit of electrical resistance?", options: ["Ohm", "Volt", "Watt", "Amp"], answer: 0 },
  { q: "What is the unit of electrical current?", options: ["Ampere", "Volt", "Ohm", "Watt"], answer: 0 },
  { q: "What is the unit of electric potential difference?", options: ["Volt", "Amp", "Ohm", "Henry"], answer: 0 },
  { q: "What does a GFCI device primarily protect against?", options: ["Ground faults that could cause electric shock", "Overloaded motors", "Lightning strikes", "Voltage spikes from the utility"], answer: 0 },
  { q: "What does an AFCI breaker primarily protect against?", options: ["Dangerous electrical arcs that can start fires", "Ground faults to a person", "Low voltage conditions", "Excess neutral current only"], answer: 0 },
  { q: "Which location most clearly requires GFCI protection for receptacles in a home?", options: ["Bathrooms", "Bedroom closets", "Hallways", "Attic storage"], answer: 0 },
  { q: "What is the main job of a circuit breaker in a panel?", options: ["To interrupt current during an overload or short circuit", "To increase the supply voltage", "To convert AC to DC", "To store electrical energy"], answer: 0 },
  { q: "What happens to a fuse when too much current flows through it?", options: ["A metal element melts and opens the circuit", "It resets itself automatically", "It boosts the voltage", "It switches the circuit to DC"], answer: 0 },
  { q: "What type of electrical power is delivered to US homes by the utility?", options: ["Alternating current", "Direct current", "Static charge", "Pulsed DC only"], answer: 0 },
  { q: "What type of power does a typical battery supply?", options: ["Direct current", "Alternating current", "Three-phase power", "High-frequency AC"], answer: 0 },
  { q: "What is the standard frequency of AC power in the United States?", options: ["60 hertz", "50 hertz", "120 hertz", "25 hertz"], answer: 0 },
  { q: "What is the common name for nonmetallic sheathed cable used in US homes?", options: ["Romex", "Conduit", "Busbar", "Wireway"], answer: 0 },
  { q: "What tool is used to measure voltage, current, and resistance?", options: ["Multimeter", "Torque wrench", "Stud finder", "Caulking gun"], answer: 0 },
  { q: "Which tool is designed to cut wire to length and strip insulation from conductors?", options: ["Wire stripper", "Hacksaw", "Chisel", "Putty knife"], answer: 0 },
  { q: "What is the main purpose of a noncontact voltage tester?", options: ["To indicate whether a wire is energized", "To measure exact resistance", "To crimp connectors", "To bend conduit"], answer: 0 },
  { q: "What are lineman's pliers commonly used for?", options: ["Gripping, twisting, and cutting wires", "Measuring voltage", "Soldering joints", "Stripping coaxial cable only"], answer: 0 },
  { q: "What is electrical conduit primarily used for?", options: ["To enclose and protect electrical wires", "To increase circuit voltage", "To store extra current", "To ground the neutral bar"], answer: 0 },
  { q: "What is the large switch at the top of a typical service panel called?", options: ["The main breaker", "The neutral bus", "The grounding electrode", "The meter base"], answer: 0 },
  { q: "What is a common cause of a tripped circuit breaker?", options: ["Plugging in too many high-wattage devices on one circuit", "Using the correct wire gauge", "Turning off a light switch", "Tightening a ground screw"], answer: 0 },
  { q: "A short circuit occurs when current takes what kind of path?", options: ["An unintended low-resistance path", "A longer path through more devices", "A path only through the ground rod", "A path that lowers the current to zero"], answer: 0 },
  { q: "In a series circuit, how does current behave?", options: ["The same current flows through every component", "Current is different in each component", "Current only flows in the first device", "Current doubles at each component"], answer: 0 },
  { q: "In a simple parallel circuit, what is true about the voltage across each branch?", options: ["Each branch has the same voltage", "Voltage adds up across branches", "Only one branch receives voltage", "Voltage is always zero"], answer: 0 },
  { q: "How many amps does a 120-volt, 1800-watt heater draw?", options: ["15 amps", "10 amps", "20 amps", "8 amps"], answer: 0 },
  { q: "Using Ohm's law, what current flows when 120 volts is applied across 60 ohms?", options: ["2 amps", "0.5 amps", "180 amps", "60 amps"], answer: 0 },
  { q: "What is the purpose of the equipment grounding conductor?", options: ["To provide a safe path for fault current", "To carry normal load current", "To raise the system voltage", "To replace the neutral wire"], answer: 0 },
  { q: "Bonding in an electrical system mainly does what?", options: ["Connects metal parts together to keep them at the same potential", "Increases the resistance of the panel", "Converts AC into DC", "Limits the supply frequency"], answer: 0 },
  { q: "What is the standard receptacle amperage for most US general-purpose 120-volt outlets?", options: ["15 amps", "30 amps", "50 amps", "5 amps"], answer: 0 },
  { q: "Which type of outlet has a T-shaped slot to accept a 20-amp plug?", options: ["A 20-amp receptacle", "A standard 15-amp receptacle", "A 240-volt dryer receptacle", "A low-voltage doorbell terminal"], answer: 0 },
  { q: "What does increasing resistance do to current if voltage stays the same?", options: ["Current decreases", "Current increases", "Current stays exactly the same", "Current becomes infinite"], answer: 0 },
  { q: "Where are AFCI protections most commonly required in newer homes?", options: ["Bedroom circuits", "Outdoor ground rods", "The utility transformer", "The water heater only"], answer: 0 },
  { q: "What is the purpose of a service panel's neutral bus bar?", options: ["To provide a common connection point for neutral conductors", "To boost incoming voltage", "To store backup power", "To act as the main fuse"], answer: 0 },
  { q: "Why should you turn off the breaker before working on a circuit?", options: ["To remove power and reduce the risk of shock", "To increase the voltage for testing", "To charge the wires faster", "To reset the electric meter"], answer: 0 },
  { q: "What does a higher AWG number indicate about a wire?", options: ["A thinner wire", "A thicker wire", "A longer wire", "A higher voltage rating"], answer: 0 },
  { q: "Which pair of devices would most likely overload a single 15-amp kitchen circuit?", options: ["A toaster and a microwave running at once", "A single phone charger", "One LED night light", "A clock radio by itself"], answer: 0 },
];

export const hvac = [
  { q: "In the refrigeration cycle, which component raises the pressure of the refrigerant?", options: ["Compressor", "Evaporator", "Condenser", "Expansion valve"], answer: 0 },
  { q: "What does the evaporator coil do in an air conditioning system?", options: ["Absorbs heat from indoor air", "Rejects heat to the outdoors", "Compresses the refrigerant", "Stores excess refrigerant"], answer: 0 },
  { q: "Where does the condenser coil release the heat it carries?", options: ["To the outdoor air", "Into the indoor living space", "Into the supply ductwork", "Into the condensate drain"], answer: 0 },
  { q: "How many BTUs per hour equal one ton of cooling?", options: ["12,000", "1,000", "5,000", "24,000"], answer: 0 },
  { q: "What does the abbreviation BTU stand for?", options: ["British Thermal Unit", "Basic Temperature Unit", "British Temperature Unit", "Boiler Transfer Unit"], answer: 0 },
  { q: "Which efficiency rating is used for the cooling performance of an air conditioner?", options: ["SEER", "AFUE", "HSPF", "MERV"], answer: 0 },
  { q: "Which rating measures the heating efficiency of a gas furnace?", options: ["AFUE", "SEER", "HSPF", "EER"], answer: 0 },
  { q: "Which rating measures the heating efficiency of a heat pump?", options: ["HSPF", "SEER", "AFUE", "MERV"], answer: 0 },
  { q: "What does SEER stand for?", options: ["Seasonal Energy Efficiency Ratio", "Standard Energy Efficiency Rating", "Seasonal Electric Efficiency Ratio", "System Energy Efficiency Rating"], answer: 0 },
  { q: "What does AFUE stand for?", options: ["Annual Fuel Utilization Efficiency", "Average Furnace Usage Efficiency", "Annual Furnace Utilization Energy", "Adjusted Fuel Use Estimate"], answer: 0 },
  { q: "The refrigerant R-22 is also commonly known by what trade name?", options: ["Freon", "Puron", "Suva", "Genetron"], answer: 0 },
  { q: "Why was R-22 refrigerant phased out?", options: ["It damages the ozone layer", "It is too expensive to make", "It does not cool well", "It is flammable and unsafe"], answer: 0 },
  { q: "Which refrigerant became a common replacement for R-22 in residential systems?", options: ["R-410A", "R-12", "R-134a", "R-502"], answer: 0 },
  { q: "Which newer refrigerant has a lower global warming potential and is used in modern systems?", options: ["R-32", "R-22", "R-12", "R-502"], answer: 0 },
  { q: "Which low-GWP refrigerant is being adopted as an R-410A replacement in new equipment?", options: ["R-454B", "R-22", "R-11", "R-500"], answer: 0 },
  { q: "What special feature lets a heat pump both heat and cool a home?", options: ["Reversing valve", "Condensate pump", "Expansion tank", "Heat exchanger"], answer: 0 },
  { q: "What is the main purpose of an expansion valve or metering device?", options: ["To lower refrigerant pressure before the evaporator", "To raise refrigerant pressure before the condenser", "To filter dust from the airflow", "To drain condensate water"], answer: 0 },
  { q: "What does a higher MERV rating on an air filter indicate?", options: ["It captures smaller particles", "It lasts a longer time", "It costs less money", "It allows more airflow"], answer: 0 },
  { q: "What does MERV stand for in air filter ratings?", options: ["Minimum Efficiency Reporting Value", "Maximum Efficiency Rating Value", "Minimum Effective Removal Value", "Mean Efficiency Reporting Value"], answer: 0 },
  { q: "In a forced-air system, what is the job of a return register?", options: ["To pull room air back to the furnace or air handler", "To deliver heated air into the room", "To drain condensate outdoors", "To hold the air filter media"], answer: 0 },
  { q: "What is the basic definition of superheat in a refrigeration system?", options: ["Temperature of vapor above its boiling point", "Temperature of liquid below its boiling point", "The pressure inside the compressor", "The airflow across the coil"], answer: 0 },
  { q: "What is the basic definition of subcooling in a refrigeration system?", options: ["Temperature of liquid below its condensing point", "Temperature of vapor above its boiling point", "The speed of the blower motor", "The size of the refrigerant line"], answer: 0 },
  { q: "What is the main purpose of the condensate drain on an air conditioner?", options: ["To carry away water from the evaporator coil", "To supply refrigerant to the compressor", "To bring fresh air into the home", "To cool the outdoor condenser"], answer: 0 },
  { q: "What tool do HVAC technicians use to measure refrigerant pressures?", options: ["Manifold gauges", "Torque wrench", "Clamp meter", "Tape measure"], answer: 0 },
  { q: "What is the primary purpose of ventilation in a building?", options: ["To bring in fresh air and remove stale air", "To raise refrigerant pressure", "To filter water from the system", "To store heat for later use"], answer: 0 },
  { q: "In which order does refrigerant flow through the four main components?", options: ["Compressor, condenser, expansion valve, evaporator", "Evaporator, expansion valve, condenser, compressor", "Condenser, compressor, evaporator, expansion valve", "Expansion valve, evaporator, compressor, condenser"], answer: 0 },
  { q: "What state is the refrigerant in as it leaves the compressor?", options: ["High-pressure hot vapor", "Low-pressure cold liquid", "Low-pressure warm vapor", "High-pressure cold liquid"], answer: 0 },
  { q: "A 3-ton air conditioner provides about how many BTUs per hour of cooling?", options: ["36,000", "12,000", "24,000", "18,000"], answer: 0 },
  { q: "What is one common fuel source for a residential furnace?", options: ["Natural gas", "Refrigerant R-410A", "Condensate water", "Compressed air"], answer: 0 },
  { q: "Besides natural gas, what is another common way furnaces produce heat?", options: ["Electric heating elements", "Solar refrigerant", "Magnetic coils", "Compressed steam"], answer: 0 },
  { q: "What is the main function of a thermostat?", options: ["To control the system based on temperature", "To filter the supply air", "To compress the refrigerant", "To drain condensate water"], answer: 0 },
  { q: "What is the main role of ductwork in a forced-air HVAC system?", options: ["To distribute conditioned air through the building", "To compress the refrigerant", "To measure indoor humidity", "To store backup heat"], answer: 0 },
  { q: "A furnace with 95 percent AFUE converts what share of its fuel into usable heat?", options: ["95 percent", "50 percent", "75 percent", "5 percent"], answer: 0 },
  { q: "A higher SEER number means the air conditioner is what?", options: ["More energy efficient", "Less energy efficient", "Larger in physical size", "Louder when running"], answer: 0 },
  { q: "Which component is typically located in the outdoor unit of a split-system AC?", options: ["Condenser coil", "Evaporator coil", "Supply register", "Furnace burner"], answer: 0 },
  { q: "Which component is typically located indoors in a split-system air conditioner?", options: ["Evaporator coil", "Condenser coil", "Outdoor fan", "Disconnect box"], answer: 0 },
  { q: "What happens to the refrigerant inside the evaporator coil?", options: ["It boils and turns into vapor", "It condenses into a liquid", "It freezes into a solid", "It stays the same temperature"], answer: 0 },
  { q: "What happens to the refrigerant inside the condenser coil?", options: ["It condenses from vapor to liquid", "It boils from liquid to vapor", "It is compressed to high pressure", "It expands to low pressure"], answer: 0 },
  { q: "What is a key advantage of a heat pump compared to electric resistance heat?", options: ["It moves heat instead of generating it, using less energy", "It runs on natural gas only", "It never needs a thermostat", "It produces no cool air at all"], answer: 0 },
  { q: "What does a clogged air filter most commonly cause in an HVAC system?", options: ["Reduced airflow and lower efficiency", "Higher refrigerant pressure outdoors", "More fresh air entering the home", "Faster condensate drainage"], answer: 0 },
  { q: "When a heat pump is in cooling mode, the indoor coil acts as what?", options: ["The evaporator", "The condenser", "The compressor", "The metering device"], answer: 0 },
  { q: "When a heat pump is in heating mode, the outdoor coil acts as what?", options: ["The evaporator", "The condenser", "The compressor", "The expansion valve"], answer: 0 },
  { q: "What does HSPF stand for?", options: ["Heating Seasonal Performance Factor", "High Speed Pressure Factor", "Heat Source Power Function", "Heating System Performance Formula"], answer: 0 },
  { q: "What is the main purpose of refrigerant in an air conditioning system?", options: ["To absorb and release heat as it changes state", "To lubricate the blower motor", "To filter dust from the air", "To add humidity to the home"], answer: 0 },
  { q: "Refrigerants R-32 and R-454B are valued for being what compared to older ones?", options: ["Lower in global warming potential", "Higher in ozone damage", "Heavier and denser", "More corrosive to copper"], answer: 0 },
];

export const alcoholExtra = [
  { q: "Which spirit is the base of a classic Negroni, alongside Campari and sweet vermouth?", options: ["Gin", "Vodka", "Rum", "Tequila"], answer: 0 },
  { q: "A traditional Old Fashioned is built with whiskey, water, bitters, and what sweetener?", options: ["Sugar", "Honey", "Maple syrup", "Agave nectar"], answer: 0 },
  { q: "The classic Manhattan cocktail combines whiskey, bitters, and which fortified wine?", options: ["Sweet vermouth", "Dry sherry", "Port", "Madeira"], answer: 0 },
  { q: "A Daiquiri in its simplest classic form contains rum, lime juice, and what?", options: ["Sugar", "Cola", "Soda water", "Egg white"], answer: 0 },
  { q: "Which orange-flavored liqueur is a key ingredient in a Cosmopolitan?", options: ["Cointreau", "Amaretto", "Kahlua", "Chambord"], answer: 0 },
  { q: "The Mai Tai is most strongly associated with which style of bar culture?", options: ["Tiki", "Speakeasy", "Sports bar", "Wine bar"], answer: 0 },
  { q: "A Mint Julep, the signature drink of the Kentucky Derby, uses what spirit?", options: ["Bourbon", "Scotch", "Rye", "Brandy"], answer: 0 },
  { q: "A Pina Colada blends rum, pineapple juice, and what coconut ingredient?", options: ["Cream of coconut", "Coconut water", "Shredded coconut", "Coconut oil"], answer: 0 },
  { q: "Irish whiskey brand Jameson is distilled in which country?", options: ["Ireland", "Scotland", "United States", "Canada"], answer: 0 },
  { q: "The rum brand Bacardi was originally founded in which country?", options: ["Cuba", "Jamaica", "Puerto Rico", "Spain"], answer: 0 },
  { q: "Jack Daniel's whiskey is produced in which US state?", options: ["Tennessee", "Kentucky", "Texas", "Virginia"], answer: 0 },
  { q: "The premium vodka brand Grey Goose originates from which country?", options: ["France", "Russia", "Sweden", "Poland"], answer: 0 },
  { q: "Patron is a well-known premium brand of which spirit?", options: ["Tequila", "Mezcal", "Rum", "Gin"], answer: 0 },
  { q: "Hennessy is a famous brand of which spirit?", options: ["Cognac", "Bourbon", "Armagnac", "Calvados"], answer: 0 },
  { q: "The dry stout Guinness is brewed at which Dublin brewery?", options: ["St. James's Gate", "Smithwick's", "Harp", "Murphy's"], answer: 0 },
  { q: "Which grape is the dominant red variety in the Burgundy region of France?", options: ["Pinot Noir", "Cabernet Sauvignon", "Merlot", "Syrah"], answer: 0 },
  { q: "The Italian red wine Chianti is made primarily from which grape?", options: ["Sangiovese", "Nebbiolo", "Barbera", "Montepulciano"], answer: 0 },
  { q: "Spanish wines labeled Rioja are made predominantly from which grape?", options: ["Tempranillo", "Garnacha", "Monastrell", "Mencia"], answer: 0 },
  { q: "Which white grape is one of the three main grapes permitted in Champagne?", options: ["Chardonnay", "Sauvignon Blanc", "Riesling", "Viognier"], answer: 0 },
  { q: "Rye whiskey in the US must be made from a mash that is at least 51 percent which grain?", options: ["Rye", "Corn", "Wheat", "Barley"], answer: 0 },
  { q: "The term single malt Scotch means the whisky comes from a single what?", options: ["Distillery", "Barrel", "Batch", "Region"], answer: 0 },
  { q: "The coffee-flavored liqueur Kahlua originated in which country?", options: ["Mexico", "Colombia", "Brazil", "Jamaica"], answer: 0 },
  { q: "Amaretto is a liqueur known for its flavor reminiscent of which nut or pit?", options: ["Almond", "Hazelnut", "Walnut", "Pistachio"], answer: 0 },
  { q: "Chambord is a French liqueur flavored primarily with which fruit?", options: ["Raspberry", "Blackcurrant", "Cherry", "Blackberry"], answer: 0 },
  { q: "Cointreau belongs to which category of orange-flavored liqueur?", options: ["Triple sec", "Bitter curacao", "Schnapps", "Amaro"], answer: 0 },
  { q: "The Bordeaux region is best known for red blends led by which two grapes?", options: ["Cabernet Sauvignon and Merlot", "Pinot Noir and Gamay", "Syrah and Grenache", "Malbec and Tannat"], answer: 0 },
  { q: "The herbal liqueur Jagermeister, often served chilled, comes from which country?", options: ["Germany", "Austria", "Switzerland", "Netherlands"], answer: 0 },
  { q: "A Cosmopolitan cocktail gets its pink color mainly from which juice?", options: ["Cranberry", "Pomegranate", "Grapefruit", "Tomato"], answer: 0 },
  { q: "A classic Martini is made from gin and which fortified wine?", options: ["Dry vermouth", "Sweet vermouth", "Port", "Sherry"], answer: 0 },
  { q: "Tequila labeled anejo has been aged for how long?", options: ["One to three years", "Less than a week", "A few hours", "Over fifty years"], answer: 0 },
  { q: "Which famous cocktail is associated with James Bond, shaken not stirred?", options: ["The Martini", "The Margarita", "The Mojito", "The Negroni"], answer: 0 },
  { q: "Champagne is made sparkling by a second fermentation that produces what gas?", options: ["Carbon dioxide", "Oxygen", "Nitrogen", "Hydrogen"], answer: 0 },
  { q: "The Aperol Spritz combines prosecco, soda, and which bitter aperitif?", options: ["Aperol", "Campari", "Fernet", "Cynar"], answer: 0 },
];

export const medicalExtra = [
  { q: "Which gland is known as the master gland of the endocrine system?", options: ["Pituitary gland", "Thyroid gland", "Adrenal gland", "Pancreas"], answer: 0 },
  { q: "The medical suffix -itis refers to what condition?", options: ["Inflammation", "Removal", "Enlargement", "Bleeding"], answer: 0 },
  { q: "What is the longest bone in the human body?", options: ["Femur", "Tibia", "Humerus", "Fibula"], answer: 0 },
  { q: "Which scientist discovered penicillin in 1928?", options: ["Alexander Fleming", "Louis Pasteur", "Joseph Lister", "Edward Jenner"], answer: 0 },
  { q: "The medical prefix cardio- relates to which organ?", options: ["Heart", "Liver", "Kidney", "Lung"], answer: 0 },
  { q: "What is the smallest bone in the human body?", options: ["Stapes", "Malleus", "Incus", "Hyoid"], answer: 0 },
  { q: "The suffix -ectomy means what in medical terms?", options: ["Surgical removal", "Inflammation", "Examination", "Repair"], answer: 0 },
  { q: "How many pairs of ribs does a typical human have?", options: ["12 pairs", "10 pairs", "14 pairs", "11 pairs"], answer: 0 },
  { q: "Who developed the first smallpox vaccine?", options: ["Edward Jenner", "Jonas Salk", "Alexander Fleming", "Robert Koch"], answer: 0 },
  { q: "Which scientist discovered x-rays in 1895?", options: ["Wilhelm Roentgen", "Marie Curie", "Albert Einstein", "Antoine Becquerel"], answer: 0 },
  { q: "The hormone adrenaline is produced by which glands?", options: ["Adrenal glands", "Thyroid glands", "Salivary glands", "Pituitary gland"], answer: 0 },
  { q: "Which part of the brain controls balance and coordination?", options: ["Cerebellum", "Cerebrum", "Medulla", "Hypothalamus"], answer: 0 },
  { q: "Red blood cells are produced primarily in which part of the body?", options: ["Bone marrow", "Liver", "Spleen", "Kidneys"], answer: 0 },
  { q: "The prefix hepato- refers to which organ?", options: ["Liver", "Heart", "Stomach", "Brain"], answer: 0 },
  { q: "Which sense is associated with the cochlea?", options: ["Hearing", "Sight", "Smell", "Taste"], answer: 0 },
  { q: "A deficiency of vitamin D in children causes which condition?", options: ["Rickets", "Scurvy", "Anemia", "Goiter"], answer: 0 },
  { q: "Which French scientist developed the process of pasteurization?", options: ["Louis Pasteur", "Alexander Fleming", "Edward Jenner", "Joseph Lister"], answer: 0 },
  { q: "The thyroid gland is located in which part of the body?", options: ["Neck", "Abdomen", "Chest", "Pelvis"], answer: 0 },
  { q: "Which muscle is the largest in the human body?", options: ["Gluteus maximus", "Biceps", "Quadriceps", "Deltoid"], answer: 0 },
  { q: "The Achilles tendon connects the calf muscle to which bone?", options: ["Heel bone", "Shin bone", "Thigh bone", "Ankle bone"], answer: 0 },
  { q: "A deficiency of which vitamin causes night blindness?", options: ["Vitamin A", "Vitamin C", "Vitamin D", "Vitamin B12"], answer: 0 },
  { q: "Which white blood cells are central to the immune response?", options: ["Lymphocytes", "Platelets", "Erythrocytes", "Hemoglobin"], answer: 0 },
  { q: "The prefix derma- relates to which part of the body?", options: ["Skin", "Bone", "Muscle", "Nerve"], answer: 0 },
  { q: "Which gas do the lungs primarily remove from the body?", options: ["Carbon dioxide", "Oxygen", "Nitrogen", "Hydrogen"], answer: 0 },
  { q: "Which part of the digestive system absorbs most nutrients?", options: ["Small intestine", "Stomach", "Large intestine", "Esophagus"], answer: 0 },
  { q: "The medical suffix -ology means the study of what?", options: ["A subject or science", "Removal of tissue", "Inflammation", "Pain"], answer: 0 },
  { q: "Which hormone regulates blood sugar by lowering it?", options: ["Insulin", "Glucagon", "Adrenaline", "Cortisol"], answer: 0 },
  { q: "Which surgeon pioneered antiseptic surgery using carbolic acid?", options: ["Joseph Lister", "Louis Pasteur", "Alexander Fleming", "William Harvey"], answer: 0 },
  { q: "The retina is found in which sensory organ?", options: ["Eye", "Ear", "Nose", "Tongue"], answer: 0 },
  { q: "Which English physician first described the circulation of blood?", options: ["William Harvey", "Edward Jenner", "Joseph Lister", "Alexander Fleming"], answer: 0 },
  { q: "What is the basic functional unit of the nervous system?", options: ["Neuron", "Nephron", "Alveolus", "Villus"], answer: 0 },
  { q: "Which vitamin is needed for proper blood clotting?", options: ["Vitamin K", "Vitamin C", "Vitamin D", "Vitamin B6"], answer: 0 },
  { q: "The medical prefix nephro- relates to which organ?", options: ["Kidney", "Liver", "Lung", "Heart"], answer: 0 },
  { q: "How many lobes does the right lung have?", options: ["Three", "Two", "Four", "One"], answer: 0 },
  { q: "Which bone protects the brain?", options: ["The skull", "The sternum", "The pelvis", "The scapula"], answer: 0 },
  { q: "What is the largest part of the human brain?", options: ["The cerebrum", "The cerebellum", "The brainstem", "The thalamus"], answer: 0 },
  { q: "Which scientist discovered the polio vaccine in the 1950s?", options: ["Jonas Salk", "Alexander Fleming", "Edward Jenner", "Marie Curie"], answer: 0 },
  { q: "The prefix osteo- relates to what part of the body?", options: ["Bone", "Skin", "Blood", "Nerve"], answer: 0 },
  { q: "Which organ stores and concentrates bile?", options: ["Gallbladder", "Pancreas", "Spleen", "Appendix"], answer: 0 },
  { q: "What is the medical term for a doctor who specializes in the heart?", options: ["Cardiologist", "Neurologist", "Dermatologist", "Nephrologist"], answer: 0 },
  { q: "Which type of blood cell helps the blood to clot?", options: ["Platelets", "Red blood cells", "Lymphocytes", "Plasma cells"], answer: 0 },
];

export const usacanadaExtra = [
  { q: "What is the capital of the US state of Texas?", options: ["Austin", "Houston", "Dallas", "San Antonio"], answer: 0 },
  { q: "What is the capital of the US state of California?", options: ["Sacramento", "Los Angeles", "San Francisco", "San Diego"], answer: 0 },
  { q: "What is the capital of the US state of New York?", options: ["Albany", "New York City", "Buffalo", "Rochester"], answer: 0 },
  { q: "What is the capital of the US state of Florida?", options: ["Tallahassee", "Miami", "Orlando", "Tampa"], answer: 0 },
  { q: "What is the capital of the US state of Illinois?", options: ["Springfield", "Chicago", "Peoria", "Naperville"], answer: 0 },
  { q: "What is the capital of the Canadian province of Quebec?", options: ["Quebec City", "Montreal", "Laval", "Gatineau"], answer: 0 },
  { q: "What is the capital of the Canadian province of Alberta?", options: ["Edmonton", "Calgary", "Red Deer", "Lethbridge"], answer: 0 },
  { q: "What is the capital of the Canadian province of British Columbia?", options: ["Victoria", "Vancouver", "Surrey", "Kelowna"], answer: 0 },
  { q: "What is the capital of the Canadian province of Manitoba?", options: ["Winnipeg", "Brandon", "Steinbach", "Thompson"], answer: 0 },
  { q: "What is the capital of the Canadian province of Nova Scotia?", options: ["Halifax", "Sydney", "Dartmouth", "Truro"], answer: 0 },
  { q: "What is the capital of the Canadian province of Saskatchewan?", options: ["Regina", "Saskatoon", "Moose Jaw", "Prince Albert"], answer: 0 },
  { q: "Which US state is nicknamed the Sunshine State?", options: ["Florida", "California", "Arizona", "Hawaii"], answer: 0 },
  { q: "Which US state is nicknamed the Lone Star State?", options: ["Texas", "Oklahoma", "Arizona", "Nevada"], answer: 0 },
  { q: "Which US state is nicknamed the Golden State?", options: ["California", "Nevada", "Colorado", "Florida"], answer: 0 },
  { q: "Which US state is nicknamed the Empire State?", options: ["New York", "New Jersey", "Pennsylvania", "Ohio"], answer: 0 },
  { q: "Which Canadian province uses the slogan Land of Living Skies?", options: ["Saskatchewan", "Manitoba", "Alberta", "Ontario"], answer: 0 },
  { q: "In which US state is Yellowstone National Park primarily located?", options: ["Wyoming", "Montana", "Idaho", "Colorado"], answer: 0 },
  { q: "In which US state is the Grand Canyon located?", options: ["Arizona", "Nevada", "Utah", "New Mexico"], answer: 0 },
  { q: "In which Canadian province is Banff National Park located?", options: ["Alberta", "British Columbia", "Saskatchewan", "Manitoba"], answer: 0 },
  { q: "What is the tallest mountain in North America?", options: ["Denali", "Mount Logan", "Mount Whitney", "Mount Rainier"], answer: 0 },
  { q: "What is the highest mountain in Canada?", options: ["Mount Logan", "Mount Robson", "Denali", "Mount Columbia"], answer: 0 },
  { q: "Which river flows through the Grand Canyon?", options: ["Colorado River", "Snake River", "Columbia River", "Rio Grande"], answer: 0 },
  { q: "In which year did the United States declare independence?", options: ["1776", "1781", "1789", "1763"], answer: 0 },
  { q: "In which year did Canadian Confederation take place?", options: ["1867", "1776", "1812", "1901"], answer: 0 },
  { q: "Who was the first President of the United States?", options: ["George Washington", "Thomas Jefferson", "John Adams", "Benjamin Franklin"], answer: 0 },
  { q: "Who was the first Prime Minister of Canada?", options: ["John A. Macdonald", "Wilfrid Laurier", "Robert Borden", "William Lyon Mackenzie King"], answer: 0 },
  { q: "Which US President is featured on the one dollar bill?", options: ["George Washington", "Abraham Lincoln", "Thomas Jefferson", "Benjamin Franklin"], answer: 0 },
  { q: "Which US President delivered the Gettysburg Address?", options: ["Abraham Lincoln", "Ulysses S. Grant", "Andrew Johnson", "Theodore Roosevelt"], answer: 0 },
  { q: "What symbol is featured at the center of the Canadian flag?", options: ["A maple leaf", "A beaver", "A fleur-de-lis", "A crown"], answer: 0 },
  { q: "What bird is the national bird of the United States?", options: ["Bald eagle", "Wild turkey", "Golden eagle", "Osprey"], answer: 0 },
  { q: "How many stars are on the current flag of the United States?", options: ["50", "48", "52", "13"], answer: 0 },
  { q: "The city of Seattle is located in which US state?", options: ["Washington", "Oregon", "California", "Idaho"], answer: 0 },
  { q: "The city of New Orleans is located in which US state?", options: ["Louisiana", "Mississippi", "Alabama", "Texas"], answer: 0 },
  { q: "The city of Montreal is located in which Canadian province?", options: ["Quebec", "Ontario", "New Brunswick", "Nova Scotia"], answer: 0 },
  { q: "Which of the Great Lakes is the largest by surface area?", options: ["Lake Superior", "Lake Huron", "Lake Michigan", "Lake Erie"], answer: 0 },
  { q: "Which US state shares the longest border with Mexico?", options: ["Texas", "Arizona", "California", "New Mexico"], answer: 0 },
  { q: "Which Canadian territory has Whitehorse as its capital?", options: ["Yukon", "Northwest Territories", "Nunavut", "Alberta"], answer: 0 },
  { q: "Which US state is known as the Aloha State?", options: ["Hawaii", "Florida", "California", "Alaska"], answer: 0 },
  { q: "Which Canadian city is known for the Calgary Stampede?", options: ["Calgary", "Edmonton", "Winnipeg", "Regina"], answer: 0 },
  { q: "Which two US states are not part of the contiguous mainland?", options: ["Alaska and Hawaii", "Texas and Florida", "Maine and Vermont", "Oregon and Nevada"], answer: 0 },
  { q: "The Liberty Bell is a historic landmark in which US city?", options: ["Philadelphia", "Boston", "Washington", "New York City"], answer: 0 },
  { q: "Which ocean borders the US state of California?", options: ["Pacific Ocean", "Atlantic Ocean", "Arctic Ocean", "Indian Ocean"], answer: 0 },
  { q: "Which Canadian province is the only officially bilingual one?", options: ["New Brunswick", "Quebec", "Ontario", "Manitoba"], answer: 0 },
];
