// "Who's most likely to..." prompts. FILTHY by default; CLEAN with the toggle.

export const FILTHY = [
  "Who's most likely to get kicked out of a bar?",
  "Who's most likely to text their ex at 3 in the morning?",
  "Who's most likely to throw up in an Uber?",
  "Who's most likely to wake up in a stranger's bed?",
  "Who's most likely to get arrested on a night out?",
  "Who's most likely to hook up with someone they just met?",
  "Who's most likely to drunk dial their boss?",
  "Who's most likely to lose their pants at a party?",
  "Who's most likely to get a regrettable tattoo while wasted?",
  "Who's most likely to flash a cop?",
  "Who's most likely to slide into a celebrity's DMs?",
  "Who's most likely to be banned from a dating app?",
  "Who's most likely to start a fight over nothing?",
  "Who's most likely to pass out before midnight?",
  "Who's most likely to send a nude to the wrong person?",
  "Who's most likely to sleep with their best friend's ex?",
  "Who's most likely to brag about their body count?",
  "Who's most likely to puke and rally?",
  "Who's most likely to get caught hooking up in public?",
  "Who's most likely to swipe right on their coworker?",
  "Who's most likely to do a body shot off a stranger?",
  "Who's most likely to ghost someone after one night?",
  "Who's most likely to cry while drunk?",
  "Who's most likely to skinny dip in a hotel pool?",
  "Who's most likely to fake an orgasm?",
  "Who's most likely to get a lap dance and fall in love?",
  "Who's most likely to wake up still drunk for work?",
  "Who's most likely to steal a road sign while hammered?",
  "Who's most likely to have a one-night stand on vacation?",
  "Who's most likely to mix way too many drinks and regret it?",
  "Who's most likely to send a thirst trap after two glasses of wine?",
  "Who's most likely to get caught sexting at work?",
  "Who's most likely to make out with a stranger on the dance floor?",
  "Who's most likely to lose their phone and their dignity in one night?",
  "Who's most likely to end up on a stripper pole at the party?",
];

export const CLEAN = [
  "Who's most likely to become a millionaire?",
  "Who's most likely to cry at a movie?",
  "Who's most likely to trip over their own feet?",
  "Who's most likely to talk to their pet like a person?",
  "Who's most likely to get lost using a map app?",
  "Who's most likely to win a hot dog eating contest?",
  "Who's most likely to forget their own birthday?",
  "Who's most likely to adopt ten cats?",
  "Who's most likely to become a famous influencer?",
  "Who's most likely to laugh at the worst possible moment?",
  "Who's most likely to fall asleep during a movie?",
  "Who's most likely to burn water trying to cook?",
  "Who's most likely to win a Nobel Prize?",
  "Who's most likely to start a conversation with a stranger?",
  "Who's most likely to name their car?",
  "Who's most likely to cry tears of joy over a puppy?",
  "Who's most likely to run a marathon on a dare?",
  "Who's most likely to sing in the shower at full volume?",
  "Who's most likely to become president?",
  "Who's most likely to forget where they parked?",
  "Who's most likely to eat dessert before dinner?",
  "Who's most likely to trip on a flat sidewalk?",
  "Who's most likely to befriend every dog at the park?",
  "Who's most likely to binge a whole show in one night?",
  "Who's most likely to get way too competitive at board games?",
];
