// Open-ended prompts for Quiplash-style play. FILTHY by default; CLEAN used when
// the host turns on the clean content toggle.

export const FILTHY = [
  "The worst possible thing to whisper during sex",
  "A rejected slogan for a brand of condoms",
  "The real reason your Tinder date ghosted you",
  "What grandma found while snooping through your nightstand drawer",
  "A terrible name for a strip club",
  "The worst thing to yell during an orgasm",
  "A bad sign your one-night stand is going poorly",
  "The least sexy thing to say while undressing",
  "Why the bartender cut you off after only two drinks",
  "A horrible flavor for a flavored lubricant",
  "The worst thing to find floating in the hot tub at the party",
  "What you definitely should NOT text your boss at 2am drunk",
  "A rejected name for a gentlemen's adult magazine",
  "The grossest thing to discover in your roommate's bathroom",
  "Why you woke up naked in a stranger's bathtub",
  "The worst pickup line ever attempted at last call",
  "A terrible thing to say to your gynecologist",
  "What ruined the honeymoon suite forever",
  "The real reason the porta-potty was out of order",
  "A bad name for a sex position you just invented",
  "The worst thing to keep next to your bed for emergencies",
  "Why your Uber driver gave you one star",
  "A horrible thing to be caught doing in the office bathroom",
  "The least romantic place to hook up",
  "What the morning-after texts always leave out",
  "A terrible euphemism for going to the bathroom",
  "The worst thing to say right after taking your pants off",
  "Why the neighbors keep filing noise complaints about your bedroom",
  "A rejected ingredient for a sexy energy drink",
  "The grossest reason your date ended early",
  "What you really did with last night's leftover tequila",
  "A terrible thing to moan in your sleep next to a new partner",
  "The worst place to run out of toilet paper",
  "Why the hotel charged you a cleaning fee",
  "A horrible name for a brand of adult diapers",
  "The least appealing thing to lick off someone",
  "What got you permanently banned from the nightclub",
  "A bad excuse for why you are late and smell like vodka",
  "The worst thing to confess during drunk truth or dare",
  "Why the stripper asked you to leave",
];

export const CLEAN = [
  "The real reason the dinosaurs went extinct",
  "A terrible name for a new breakfast cereal",
  "What your dog is secretly thinking about you",
  "The worst superpower to have at a wedding",
  "A bad theme for a child's birthday party",
  "The least helpful advice to give a new parent",
  "What aliens would write in their review of Earth",
  "A terrible name for a boat",
  "The worst thing to find in your hotel minibar",
  "Why the chicken really crossed the road",
  "A horrible mascot for a hospital",
  "The least exciting prize on a game show",
  "What your cat does all day while you are at work",
  "A terrible name for a perfume aimed at toddlers",
  "The worst thing a magician could pull out of a hat",
  "A bad slogan for a funeral home",
  "The real reason your Wi-Fi keeps cutting out",
  "A horrible flavor for a birthday cake",
  "The worst possible name for a racehorse",
  "What the tooth fairy does with all those teeth",
  "A terrible thing to put on a billboard",
  "The least scary thing to dress up as for Halloween",
  "Why the vending machine ate your dollar",
  "A bad name for a self-help book",
  "The worst song to play at a funeral",
  "What your houseplants gossip about at night",
  "A terrible theme for a wedding reception",
  "The least useful invention of all time",
  "Why the GPS keeps telling you to make a U-turn",
  "A horrible name for a brand of dog food",
];
